### ISSUE TITLE
UM Profile Content Moderation not found on your Github

### ISSUE THREAD

**Issue by ghost** [MissVeronica/UM-Members-Directory-Left-Filter-Box#3]
Hello,

I'm sorry, I'm not sending this problem to the right place.

But I can't find the UM Profile Content Moderation plugin on your Github. Is this normal?

Have a nice evening,
Alexis Grolot

**Comment by MissVeronica** [comment]
Hello
Yes you are right it's set to private because I am working on an update until finished to release.

**Comment by MissVeronica** [comment]
Now you have the version 3.6.3 available for download from the public repo.
Plugin will indicate within 24 hours that the update is available too.
https://github.com/MissVeronica/um-profile-content-moderation

**Comment by alexisgrolot** [comment]
Hello,

Thank you very much, I was able to update the plugin to version 3.6.3!
